
name: Compilation Test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main/develop branch
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile_linux:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: compile the project
        run: make debug
        
      - name: run the compiler on example.memeasm
        run: ./memeasm -S -d -o example.S .github/workflows/example.memeasm
        
  compile_windows:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Compile memeasm
        shell: powershell
        run: |
          $env:Path += ";C:\msys64\mingw64\bin"
          mingw32-make.exe debug     
          
      - name: Run compiler on example.memeasm
        shell: powershell
        run: ./memeasm.exe -S -d -o example.S .github\workflows\example.memeasm
